version: '3.9'
services:
  appmain:
    build: .
    ports:
      - "8000:8000"
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=juegoroblox123
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:

  